spring.datasource.url=jdbc:mysql://db1.cpttpi1lvejf.us-east-1.rds.amazonaws.com:3306/municipalidad_la_florida?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
spring.datasource.username=admin
spring.datasource.password=224571e47a8
spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.path=/api-docs
